# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-18 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'zhongjiu_wheel',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('isselect', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'zhongjiu_cart',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default=0, max_length=10)),
                ('img', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('bigimg', models.CharField(default='', max_length=100)),
                ('smallimg1', models.CharField(default='', max_length=100)),
                ('smallimg2', models.CharField(default='', max_length=100)),
                ('smallimg3', models.CharField(default='', max_length=100)),
                ('smallimg4', models.CharField(default='', max_length=100)),
            ],
            options={
                'db_table': 'zhongjiu_goods',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('indentifier', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'zhongjiu__order',
            },
        ),
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zhongjiuApp.Goods')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zhongjiuApp.Order')),
            ],
            options={
                'db_table': 'zhongjiu__ordergoods',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=11, unique=True)),
                ('token', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'zhongjiu_user',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zhongjiuApp.User'),
        ),
        migrations.AddField(
            model_name='cart',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zhongjiuApp.Goods'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zhongjiuApp.User'),
        ),
    ]
