# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-09 09:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zhongjiuApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='banner',
            table='zhongjiu_wheel',
        ),
    ]
