# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-19 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhongjiuApp', '0003_auto_20190118_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='indentifier',
        ),
        migrations.AddField(
            model_name='order',
            name='identifier',
            field=models.CharField(default=0, max_length=256),
        ),
    ]
