# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-10 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhongjiuApp', '0005_goods_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
