# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-12 02:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zhongjiuApp', '0006_auto_20190110_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
