# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-12 02:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zhongjiuApp', '0007_remove_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='tokon',
            new_name='token',
        ),
    ]
