# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-13 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhongjiuApp', '0008_auto_20190112_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='bigimg',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='goods',
            name='smallimg1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='goods',
            name='smallimg2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='goods',
            name='smallimg3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='goods',
            name='smallimg4',
            field=models.CharField(default='', max_length=100),
        ),
    ]
