# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-14 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhongjiuApp', '0009_auto_20190113_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
