# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-15 11:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zhongjiuApp', '0010_auto_20190114_0633'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
            options={
                'db_table': 'zhongjiu_cart',
            },
        ),
        migrations.AlterModelTable(
            name='goods',
            table='zhongjiu_goods',
        ),
        migrations.AlterModelTable(
            name='user',
            table='zhongjiu_user',
        ),
        migrations.AddField(
            model_name='cart',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zhongjiuApp.Goods'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zhongjiuApp.User'),
        ),
    ]
