# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-15 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhongjiuApp', '0011_auto_20190115_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='isselect',
            field=models.BooleanField(default=True),
        ),
    ]
